version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - /data/db:/var/lib/postgresql/data
    env_file: ./server/.env
  web:
    build: ./server
    env_file: ./server/.env
    volumes:
      - ./server/logs:/usr/src/logs/
    ports:
      - "8000:8000"
    depends_on:
      - db