# Generated by Django 4.0.4 on 2022-05-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('percent_off', models.IntegerField()),
                ('duration', models.CharField(choices=[('forever', 'forever'), ('once', 'once'), ('repeating', 'repeating')], max_length=9)),
                ('duration_in_months', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('jurisdiction', models.CharField(default='RU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(choices=[('sales_tax', 'sales_tax'), ('vat', 'vat')], max_length=10)),
                ('jurisdiction', models.CharField(choices=[('US', 'US'), ('DE', 'DE'), ('RU', 'RU')], max_length=2)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inclusive', models.BooleanField()),
            ],
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['jurisdiction', 'tax_id'], name='stripe_app__jurisdi_75816e_idx'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_app.discount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_app.item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_app.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stripe_app.tax'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ManyToManyField(blank=True, to='stripe_app.discount'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['id'], name='stripe_app__id_d7173c_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['uuid'], name='stripe_app__uuid_e82350_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='stripe_app__code_4c48ec_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['uuid'], name='stripe_app__uuid_c50630_idx'),
        ),
    ]
